20170215

diff --git a/docker/api/autoconf/2 b/docker/api/autoconf/2
--- a/docker/api/autoconf/2
+++ b/docker/api/autoconf/2
@@ -3,16 +3,24 @@
 # Node details:
 TYPE=iol
 CONTROLLER=172.17.0.1
-LABEL=256
-ID=2
+LABEL=0
+ID=1
 ARGS="-g ${CONTROLLER} -i ${ID} -l ${LABEL} -f /opt/image/iol.bin -t -w R0 -- -q -n 4096 -e 1 -s 1"
 
+PID=0
 HOSTNAME=$(cat /opt/image/iourc | grep "=" | head -n1 | sed 's/\ *=.*//')
 export HOSTNAME
 
 function die {
 	echo $1
 	exit 1
+}
+
+function nodeStop {
+    if [ ${PID} -ne 0 ]; then
+        kill -SIGTERM ${PID}
+        wait ${PID}
+    fi
 }
 
 # Building the management switch
@@ -24,10 +32,10 @@ ip link set dev veth0 up &> /dev/null || die "ERROR: failed to bring veth0 inter
 brctl addif mgmt0 veth0 &> /dev/null || die "ERROR: failed to attach veth0 to mgmt0 bridge"
 iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE &> /dev/null || die "ERROR: failed to configure iptables (MASQUERADE on eth0)"
 iptables -t nat -A POSTROUTING -o mgmt0 -j MASQUERADE &> /dev/null || die "ERROR: failed to configure iptables (MASQUERADE on mgmt0)"
-iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 8022 -j DNAT --to 192.0.2.254:22 &> /dev/null || die "ERROR: failed to configure iptables (NAT ports 22 on eth0)"
-iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 8023 -j DNAT --to 192.0.2.254:23 &> /dev/null || die "ERROR: failed to configure iptables (NAT ports 23 on eth0)"
-iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 8080 -j DNAT --to 192.0.2.254:80 &> /dev/null || die "ERROR: failed to configure iptables (NAT port 80 on eth0)"
-iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 8443 -j DNAT --to 192.0.2.254:443 &> /dev/null || die "ERROR: failed to configure iptables (NAT port 443 on eth0)"
+iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 22 -j DNAT --to 192.0.2.254:22 &> /dev/null || die "ERROR: failed to configure iptables (NAT ports 22 on eth0)"
+iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 23 -j DNAT --to 192.0.2.254:23 &> /dev/null || die "ERROR: failed to configure iptables (NAT ports 23 on eth0)"
+iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j DNAT --to 192.0.2.254:80 &> /dev/null || die "ERROR: failed to configure iptables (NAT port 80 on eth0)"
+iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 443 -j DNAT --to 192.0.2.254:443 &> /dev/null || die "ERROR: failed to configure iptables (NAT port 443 on eth0)"
 iptables -t nat -A PREROUTING -i mgmt0 -p udp --dport 69 -j DNAT --to ${CONTROLLER}:69 &> /dev/null || die "ERROR: failed to configure iptables (NAT port 69 on mgmt0)"
 iptables -t nat -A PREROUTING -i mgmt0 -p tcp --dport 20 -j DNAT --to ${CONTROLLER}:20 &> /dev/null || die "ERROR: failed to configure iptables (NAT port 20 on mgmt0)"
 iptables -t nat -A PREROUTING -i mgmt0 -p tcp --dport 21 -j DNAT --to 172.17.0.1:21 &> /dev/null || die "ERROR: failed to configure iptables (NAT port 21 on mgmt0)"
@@ -46,4 +54,8 @@ curl -m 3 -s http://${CONTROLLER}/api/wrappers/wrapper_modules.py > /usr/lib/pyt
 chmod 755 /sbin/wrapper.py || die "ERROR: cannot make wrapper executable"
 
 echo "INFO: starting wrapper: /sbin/wrapper.py ${ARGS}"
-/sbin/wrapper.py ${ARGS}
+trap nodeStop SIGINT SIGTERM
+/sbin/wrapper.py ${ARGS} &
+PID=$!
+wait $PID
+exit $?
